nameOverride: ''
fullnameOverride: ''
replicaCount: 1
images:
  repositoryDirname: europe-west1-docker.pkg.dev/k8s-ci-cd-1/podtato-head
  pullPolicy: IfNotPresent
  pullSecrets: []
  tag: '1.63'
entry:
  repositoryBasename: entry
  serviceType: LoadBalancer
  loadbalancerIP: 35.195.60.0
  servicePort: 9000
  env: []
hat:
  repositoryBasename: hat
  serviceType: ClusterIP
  servicePort: 9001
  env: []
leftLeg:
  repositoryBasename: left-leg
  serviceType: ClusterIP
  servicePort: 9002
  env: []
leftArm:
  repositoryBasename: left-arm
  serviceType: ClusterIP
  servicePort: 9003
  env: []
rightLeg:
  repositoryBasename: right-leg
  serviceType: ClusterIP
  servicePort: 9004
  env: []
rightArm:
  repositoryBasename: right-arm
  serviceType: ClusterIP
  servicePort: 9005
  env: []
serviceAccount:
  create: false
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
ingress:
  enabled: false
  annotations: {}
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
